#!/usr/bin/env bash

export CLASSPATH=".:/usr/local/lib/antlr-4.8-complete.jar:$CLASSPATH"
alias antlr4='java -jar /usr/local/lib/antlr-4.8-complete.jar'
alias grun='java org.antlr.v4.gui.TestRig'

if [[ "$1"  == "-h" ]]; then
  echo "USAGE: ./build [test -f <file> | <output_dir>]"
  echo "  <output_dir> = output directory for generated python files (default is ../src/dgdl/antlr)"
  exit 1
fi

if [[ "$1" == "test" ]]; then
  if [[ -d "test" ]]; then
    rm -rf test
  fi
  mkdir test

  antlr4 -o ./test *.g4

  if [[ $? -ne 0 ]]; then
    echo "Grammar compile failed"
    exit 1
  fi

  javac ./test/*.java

  if [[ $? -ne 0 ]]; then
    echo "Antlr compile failed"
    exit 1
  fi

  if [[ "$2" == "-f" ]]; then
    TEXT=$(cat $3)

    cd ./test

    echo $TEXT | grun dgdl game -gui

    #cleanup
    rm -rf `pwd`

  else

    echo "Enter expression:"

    grun dgdl game -gui
  fi
else

  if [[ "$#" == 0 ]]; then
    OUTPUT="../src/dgdl/antlr"
  else
    OUTPUT=$1
  fi

  echo "Writing to $OUTPUT"

  if [[ -d $OUTPUT ]]; then
    rm -rf $OUTPUT
  fi
  mkdir $OUTPUT

  antlr4 -o $OUTPUT -Dlanguage=Python3 *.g4

  echo 'from dgdl.antlr.dgdlListener import dgdlListener' > $OUTPUT/__init__.py
  echo 'from dgdl.antlr.dgdlLexer import dgdlLexer' >> $OUTPUT/__init__.py
  echo 'from dgdl.antlr.dgdlParser import dgdlParser' >> $OUTPUT/__init__.py
fi
