#!/usr/bin/env bash

# Copyright (C) 2020  Centre for Argument Technology (http://arg.tech)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

export CLASSPATH=".:/usr/local/lib/antlr-4.8-complete.jar:$CLASSPATH"
alias antlr4='java -jar /usr/local/lib/antlr-4.8-complete.jar'
alias grun='java org.antlr.v4.gui.TestRig'

if [[ "$1"  == "-h" ]]; then
  echo "USAGE: ./build [test -f <file> | <output_dir>]"
  echo "  <output_dir> = output directory for generated python files (default is ../src/dgdl/antlr)"
  exit 1
fi

if [[ "$1" == "test" ]]; then
  if [[ -d "test" ]]; then
    rm -rf test
  fi
  mkdir test

  java -jar /usr/local/lib/antlr-4.8-complete.jar -o ./test *.g4

  if [[ $? -ne 0 ]]; then
    echo "Grammar compile failed"
    exit 1
  fi

  javac ./test/*.java

  if [[ $? -ne 0 ]]; then
    echo "Antlr compile failed"
    exit 1
  fi

  if [[ "$2" == "-f" ]]; then
    TEXT=$(cat $3)

    cd ./test

    echo $TEXT | java org.antlr.v4.gui.TestRig dgdl game -gui

    #cleanup
    rm -rf `pwd`

  else

    echo "Enter expression:"

    java org.antlr.v4.gui.TestRig dgdl game -gui
  fi
else

  if [[ "$#" == 0 ]]; then
    OUTPUT="../src/dgdl/antlr"
  else
    OUTPUT=$1
  fi

  echo "Writing to $OUTPUT"

  if [[ -d $OUTPUT ]]; then
    rm -rf $OUTPUT
  fi
  mkdir $OUTPUT

  java -jar /usr/local/lib/antlr-4.8-complete.jar -o $OUTPUT -Dlanguage=Python3 *.g4

  echo 'from dgdl.antlr.dgdlListener import dgdlListener' > $OUTPUT/__init__.py
  echo 'from dgdl.antlr.dgdlLexer import dgdlLexer' >> $OUTPUT/__init__.py
  echo 'from dgdl.antlr.dgdlParser import dgdlParser' >> $OUTPUT/__init__.py
fi
